RIDERSERVICE_BASE_PATH: "http://rider-service.perftest:8080"
JOBALLOCATION_BASE_PATH: "http://job-allocation-service.perftest:8080"
OPSSERVICE_BASE_PATH: "http://operations-service.perftest:8080"
OPSSERVICE_CACHE_AGE: "300"
SCHEDULER_JOB_CLEANUP: "2000"
JOBSERVICE_BASE_PATH: "http://job-service.perftest:8080"
SCHEDULER_RIDER_REBROADCAST: "5000"
COGNITO_URL_APP: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_4303LikBo
COGNITO_URL_OPS: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_xaLhzQCai
REDIS_PRIMARY_HOST: rider-perftest-elasticache-redis.l9akz6.ng.0001.apse1.cache.amazonaws.com
REDIS_READ_HOST: rider-perftest-elasticache-redis-ro.l9akz6.ng.0001.apse1.cache.amazonaws.com
