---
# Source: environment/templates/devops-config/deployment/deployment-vars-{{env}}.yml
# This file was generated at  using generator Version: 

DEPLOYMENT:
    ENV: preprod
    NAMESPACE: preprod
    CONFIG_FILES:
        - "src/main/resources/config/broadcast-service.default.yaml"
        - "src/main/resources/config/broadcast-service.preprod.yaml"

APP:
    REPLICA: 3
    HPA:
      ENABLED: 0
      MIN_REPLICA: 3
      MAX_REPLICA: 6
      CPU_UTILIZATION: 65
      MEMORY_UTILIZATION: 80
    CONTAINER:
      MEMORY:
        REQUEST: 2Gi
        LIMIT: 2Gi
      CPU:
        REQUEST: 1
        LIMIT: 2
    ENVIRONMENT:
      - KEY: logs.Dir
        VALUE: "/apps/logs/preprod/broadcast-service/"
